#%RAML 1.0 DataType
type: object
properties:
    city:
      type: string
      description: City name
      displayName: City Name
    theatreName:
      type: string
      description: Theatre Name
      displayName: Theatre Name
    location:
      type: string
      description: Location of movie theatre
      displayName: Theatre location
    movieName:
      type: string
      description: Movie Name
      displayName: Enter Movie Name
    language:
      type: string
      description: Movie language
      displayName: Movie language
    showDate: 
      type: date-only
      description: Movie show date
      displayName:  Show Date
    showTime:
       type: string
       description: Show time 
       displayName: Show time 
      
    seatType:
      type: string
      description: Theatre Seat type
      displayName: Seat Movie Name
    noOfSeats:
      type: integer
      description: No of seats you wants to book
      displayName: Number of Seats