#%RAML 1.0 NamedExample
value:
  city: Noida
  theatreName: PVR
  location: sector 51
  movieName: Bhaubali
  language: Hindi
  showDate: 2020-11-15
  showTime: 11:30:00
  seatType: Gold
  noOfSeats: 2
  