#%RAML 1.0 NamedExample
value:
-     
     id: 12
     movieName: Bhaubhali
     releaseDate: 2017-11-12
     language : Hindi
     rating: 4.5
     votes: 11000
     certificate: U/A
     movieType: Action
     duration: 180 mins
     city: Noida

-     
     id: 121
     movieName: Bhaubhali
     releaseDate: 2017-11-12
     language : Hindi
     rating: 4.5
     votes: 11000
     certificate: U/A
     movieType: Action
     duration: 180 mins
     city: Noida
    