#%RAML 1.0 NamedExample
value:
  -

    id: 123
    movieName: Bhaubali
    language: English
    name: PVR
    avialability:
      -
        showTime: 11.35
        avialableSeats: 56
    
    date: 2002-11-11
    location: sector21
    city: Noida
    
	
  -

    id: 123
    movieName: Bhaubali
    language: English
    name: PVR
    avialability:
      -
        showTime: 11.35
        avialableSeats: 56
    
    date: 2002-11-11
    location: sector21
    city: Noida
  
					
	